global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-service:5000']

  - job_name: 'crm-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['data-service:5001']